FROM  golang AS builder
ADD .. /src
WORKDIR /src
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn
RUN go mod tidy
RUN cd cmd/server && go build -o /bridge .

# final stage
FROM golang
COPY --from=builder /bridge_api ./
RUN chmod +x ./bridge
RUN mkdir -p "/src/tron_keystore/keystore"

ENTRYPOINT ["./bridge"]
