FROM golang AS builder
WORKDIR /app
ADD . /app
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn
RUN #apt-get update && apt-get install -y gcc g++ make
RUN go mod tidy
RUN go build -o /bridge_api cmd/server/main.go

FROM golang
WORKDIR /app
COPY --from=builder /bridge_api ./
RUN chmod +x ./bridge_api

ENTRYPOINT ["./bridge_api"]